spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/STK_database
    username: STK_database
    password: krB6sk8

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect